// src/data.ts
import { Venue, Person, Tag } from "./types";
import { v4 as uuidv4 } from "uuid";

/**
 * 1) Sample Tags
 */
export const sampleTags: Tag[] = [
  { id: "tech", name: "tech", count: 0, lastUsed: 0 },
  { id: "tattoos", name: "tattoos", count: 0, lastUsed: 0 },
  { id: "crypto", name: "crypto", count: 0, lastUsed: 0 },
  { id: "friendly", name: "friendly", count: 0, lastUsed: 0 },
  { id: "foodie", name: "foodie", count: 0, lastUsed: 0 },
  { id: "kind", name: "kind", count: 0, lastUsed: 0 },
  { id: "local", name: "local", count: 0, lastUsed: 0 },
  { id: "fashion", name: "fashion", count: 0, lastUsed: 0 },
  { id: "raptors", name: "raptors", count: 0, lastUsed: 0 },
  { id: "neighbour", name: "neighbour", count: 0, lastUsed: 0 },
  { id: "marketing", name: "marketing", count: 0, lastUsed: 0 },
  { id: "networker", name: "networker", count: 0, lastUsed: 0 },
  { id: "events", name: "events", count: 0, lastUsed: 0 },
  { id: "chef", name: "chef", count: 0, lastUsed: 0 },
  { id: "intense", name: "intense", count: 0, lastUsed: 0 },
  { id: "creative", name: "creative", count: 0, lastUsed: 0 },
  { id: "design", name: "design", count: 0, lastUsed: 0 },
  { id: "sketching", name: "sketching", count: 0, lastUsed: 0 },
  { id: "dj", name: "dj", count: 0, lastUsed: 0 },
  { id: "music", name: "music", count: 0, lastUsed: 0 },
  { id: "nightlife", name: "nightlife", count: 0, lastUsed: 0 },
  { id: "vibes", name: "vibes", count: 0, lastUsed: 0 },
  { id: "photography", name: "photography", count: 0, lastUsed: 0 },
  { id: "social", name: "social", count: 0, lastUsed: 0 },
  { id: "bartender", name: "bartender", count: 0, lastUsed: 0 },
  { id: "chill", name: "chill", count: 0, lastUsed: 0 },
  { id: "mezcal", name: "mezcal", count: 0, lastUsed: 0 },
  { id: "hospitality", name: "hospitality", count: 0, lastUsed: 0 },
  { id: "law", name: "law", count: 0, lastUsed: 0 },
  { id: "debate", name: "debate", count: 0, lastUsed: 0 },
  { id: "ai", name: "ai", count: 0, lastUsed: 0 },
  { id: "smart", name: "smart", count: 0, lastUsed: 0 },
  { id: "energetic", name: "energetic", count: 0, lastUsed: 0 },
  { id: "fast", name: "fast", count: 0, lastUsed: 0 },
  { id: "confident", name: "confident", count: 0, lastUsed: 0 },
  { id: "funny", name: "funny", count: 0, lastUsed: 0 },
  { id: "health", name: "health", count: 0, lastUsed: 0 },
  { id: "calm", name: "calm", count: 0, lastUsed: 0 },
];

/**
 * 2) Sample Venues
 */
export const sampleVenues: Venue[] = [
  {
    id: uuidv4(),
    name: "The Tipsy Owl",
    locationTag: "Toronto, ON",
    coords: { lat: 43.6475, lon: -79.3800 },
  },
  {
    id: uuidv4(),
    name: "Blue Bayou",
    locationTag: "Toronto, ON",
    coords: { lat: 43.6450, lon: -79.3900 },
  },
  {
    id: uuidv4(),
    name: "Craft & Vine",
    locationTag: "Toronto, ON",
    coords: { lat: 43.6441, lon: -79.3897 },
  },
  {
    id: uuidv4(),
    name: "The Garden Lounge",
    locationTag: "Toronto, ON",
    coords: { lat: 43.6480, lon: -79.3850 },
  },
];

/**
 * 3) Sample People
 */
export const samplePeople: Person[] = [
  {
    id: uuidv4(),
    name: "Grant Bass",
    position: "Software Engineer",
    description: "Met after a tech meetup—smart, energetic.",
    venueId: sampleVenues[0].id,
    dateMet: "2025-05-03T21:30:00.000Z",
    createdAt: "2025-05-03T21:30:00.000Z",
    tags: ["tech", "smart", "energetic"],
  },
  {
    id: uuidv4(),
    name: "Sarah Mitchell",
    position: "Nurse",
    description: "Friendly and kind, loves local eateries.",
    venueId: sampleVenues[1].id,
    dateMet: "2025-05-04T20:15:00.000Z",
    createdAt: "2025-05-04T20:15:00.000Z",
    tags: ["friendly", "kind", "local"],
  },
  {
    id: uuidv4(),
    name: "Alex Wong",
    position: "Software Engineer",
    description: "Into crypto and blockchain tech.",
    venueId: sampleVenues[2].id,
    dateMet: "2025-04-25T23:00:00.000Z",
    createdAt: "2025-04-25T23:00:00.000Z",
    tags: ["crypto", "tech", "creative"],
  },
  {
    id: uuidv4(),
    name: "Leila D’Souza",
    position: "Marketing Coordinator",
    description: "Always networking at events.",
    venueId: sampleVenues[0].id,
    dateMet: "2025-05-07T20:00:00.000Z",
    createdAt: "2025-05-07T20:00:00.000Z",
    tags: ["marketing", "networker", "events"],
  },
  {
    id: uuidv4(),
    name: "Marcus James",
    position: "Chef",
    description: "Creative chef with intense passion for food.",
    venueId: sampleVenues[2].id,
    dateMet: "2025-05-09T18:45:00.000Z",
    createdAt: "2025-05-09T18:45:00.000Z",
    tags: ["chef", "intense", "foodie"],
  },
  {
    id: uuidv4(),
    name: "Ella Chen",
    position: "UX Designer",
    description: "Loves design and sketching new concepts.",
    venueId: sampleVenues[3].id,
    dateMet: "2025-04-30T19:20:00.000Z",
    createdAt: "2025-04-30T19:20:00.000Z",
    tags: ["design", "sketching", "creative"],
  },
  {
    id: uuidv4(),
    name: "Tyrese Cole",
    position: "DJ",
    description: "Spun vinyl and talked nightlife vibes.",
    venueId: sampleVenues[1].id,
    dateMet: "2025-05-12T01:00:00.000Z",
    createdAt: "2025-05-12T01:00:00.000Z",
    tags: ["dj", "music", "nightlife"],
  },
  {
    id: uuidv4(),
    name: "Dani Romero",
    position: "Photographer",
    description: "Professional photographer shooting social events.",
    venueId: sampleVenues[3].id,
    dateMet: "2025-05-12T23:30:00.000Z",
    createdAt: "2025-05-12T23:30:00.000Z",
    tags: ["photography", "social", "creative"],
  },
  {
    id: uuidv4(),
    name: "Jamal Peterson",
    position: "Bartender",
    description: "Chill bartender mixing mezcal cocktails.",
    venueId: sampleVenues[0].id,
    dateMet: "2025-05-14T00:30:00.000Z",
    createdAt: "2025-05-14T00:30:00.000Z",
    tags: ["bartender", "chill", "mezcal"],
  },
  {
    id: uuidv4(),
    name: "Ava Nguyen",
    position: "Law Student",
    description: "Debated AI ethics passionately.",
    venueId: sampleVenues[1].id,
    dateMet: "2025-05-15T21:00:00.000Z",
    createdAt: "2025-05-15T21:00:00.000Z",
    tags: ["law", "debate", "ai"],
  },
  {
    id: uuidv4(),
    name: "Julian Reyes",
    position: "Barback",
    description: "Fast and efficient support staff.",
    venueId: sampleVenues[1].id,
    dateMet: "2025-04-22T22:00:00.000Z",
    createdAt: "2025-04-22T22:00:00.000Z",
    tags: ["hospitality", "fast", "energetic"],
  },
  {
    id: uuidv4(),
    name: "Nina Kapoor",
    position: "Marketing Coordinator",
    description: "Organizes top-tier events.",
    venueId: sampleVenues[0].id,
    dateMet: "2025-05-08T18:30:00.000Z",
    createdAt: "2025-05-08T18:30:00.000Z",
    tags: ["events", "marketing", "networker"],
  },
  {
    id: uuidv4(),
    name: "Omar Williams",
    position: "Chef",
    description: "Trendy food truck guru.",
    venueId: sampleVenues[2].id,
    dateMet: "2025-05-11T17:00:00.000Z",
    createdAt: "2025-05-11T17:00:00.000Z",
    tags: ["chef", "foodie", "creative"],
  },
  {
    id: uuidv4(),
    name: "Tasha Green",
    position: "Photographer",
    description: "Retro vibes and film photography.",
    venueId: sampleVenues[3].id,
    dateMet: "2025-05-13T19:30:00.000Z",
    createdAt: "2025-05-13T19:30:00.000Z",
    tags: ["photography", "vibes", "artistic"],
  },
  {
    id: uuidv4(),
    name: "David Lee",
    position: "Software Engineer",
    description: "Connecting devs to meetups.",
    venueId: sampleVenues[0].id,
    dateMet: "2025-05-06T19:00:00.000Z",
    createdAt: "2025-05-06T19:00:00.000Z",
    tags: ["tech", "networker", "friendly"],
  },
  {
    id: uuidv4(),
    name: "Lena Tran",
    position: "UX Designer",
    description: "Detail-oriented design thinker.",
    venueId: sampleVenues[1].id,
    dateMet: "2025-05-10T18:00:00.000Z",
    createdAt: "2025-05-10T18:00:00.000Z",
    tags: ["design", "kind", "creative"],
  },
  {
    id: uuidv4(),
    name: "Chris McMillan",
    position: "DJ",
    description: "Deep house vinyl specialist.",
    venueId: sampleVenues[3].id,
    dateMet: "2025-05-04T20:30:00.000Z",
    createdAt: "2025-05-04T20:30:00.000Z",
    tags: ["music", "nightlife", "vibes"],
  },
  {
    id: uuidv4(),
    name: "Rhea Patel",
    position: "Law Student",
    description: "AI ethics debate champion.",
    venueId: sampleVenues[1].id,
    dateMet: "2025-05-15T21:15:00.000Z",
    createdAt: "2025-05-15T21:15:00.000Z",
    tags: ["law", "debate", "ai"],
  },
  {
    id: uuidv4(),
    name: "Tony Delvecchio",
    position: "Bartender",
    description: "Jokes and mezcal expertise.",
    venueId: sampleVenues[0].id,
    dateMet: "2025-05-02T20:45:00.000Z",
    createdAt: "2025-05-02T20:45:00.000Z",
    tags: ["bartender", "funny", "mezcal"],
  },
  {
    id: uuidv4(),
    name: "Zoë Kim",
    position: "Nurse",
    description: "Calm composure in health crisis.",
    venueId: sampleVenues[1].id,
    dateMet: "2025-05-04T21:00:00.000Z",
    createdAt: "2025-05-04T21:00:00.000Z",
    tags: ["health", "calm", "kind"],
  },
];
